### ISSUE TITLE
Python traceback when deleting data from rules: ValueError at /rules/rule/2000334/delete

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/scirius#81] opened 2016-10-14 17:41 UTC
When deleting data generated by rules from scirius I am getting the following error:

No JSON object could be decoded
Request Method:	POST
Request URL:	http://ids.corp.domain.com:8000/rules/rule/2000334/delete
Django Version:	1.8.15
Exception Type:	ValueError
Exception Value:	
No JSON object could be decoded
Exception Location:	/usr/lib64/python2.7/json/decoder.py in raw_decode, line 383
Python Executable:	/bin/python
Python Version:	2.7.5
Python Path:	
['/usr/lib/python2.7/site-packages/git/ext/gitdb',
 '/opt/scirius',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gitdb/ext/smmap']
Server time:	Fri, 14 Oct 2016 19:39:44 +0200

This is my local_settings.py for scirius:

import os

DBBACKUP_STORAGE = 'dbbackup.storage.filesystem_storage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/opt/scirius/backups/'}

ELASTICSEARCH_ADDRESS = "127.0.0.1:9200"
USE_ELASTICSEARCH = True
ELASTICSEARCH_2X = True

KIBANA_URL = "http://ids.corp.domain.com:5601"
USE_KIBANA = True
KIBANA_INDEX = ".kibana"

KIBANA_VERSION=4

KIBANA_DASHBOARDS_PATH = "/opt/KTS/"

USE_SURICATA_STATS = True
USE_LOGSTASH_STATS = True

ELASTICSEARCH_LOGSTASH_ALERT_INDEX="logstash-alert-"

**Comment by regit** [comment] 2016-10-18 17:29
From IRC discussion, this is caused by delete-by-query plugin not being installed on Elasticsearch. Message should be improved to clearly state that.

**Comment by regit** [comment] 2016-10-18 19:25
Fixed by aec5987e168f629391fb24a4be869760317cbda8

**Closed by regit** 2016-10-18 19:25 UTC
